# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CronDoctor < Formula
  desc "Audit your crontabs"
  homepage "https://github.com/HeytalePazguato/cron-doctor"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.1/cron-doctor_darwin_amd64.tar.gz"
      sha256 "3f50fcc3b3ffd6c4f5312bee4ab1e03f7aa6246ee58e685c793f2849db91e2e9"

      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.1/cron-doctor_darwin_arm64.tar.gz"
      sha256 "eef1c09bc556827a25c0dd473c7e6a1906b5ba9b792e434e1c33c8bd477b01c2"

      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.1/cron-doctor_linux_amd64.tar.gz"
      sha256 "693577149ba1548ac3eac0a5e54ef7e7783564c95d40b4aac2f7b5fab899809a"
      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.1/cron-doctor_linux_arm64.tar.gz"
      sha256 "5a21074e2f365a3af5778c5b485283feb9222410e1a86541ed26b230225097e1"
      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
  end

  test do
    system "#{bin}/cron-doctor", "--version"
  end
end
