# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CronDoctor < Formula
  desc "Audit your crontabs"
  homepage "https://github.com/HeytalePazguato/cron-doctor"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.2/cron-doctor_darwin_amd64.tar.gz"
      sha256 "57ffadade48f7f1d4a3d451f93ca5caf4520529a30fb48b799f6734d11fff79f"

      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.2/cron-doctor_darwin_arm64.tar.gz"
      sha256 "c57743fc8172d1cf76de019dfb784d5b545c9f5123af58561016732121b19914"

      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.2/cron-doctor_linux_amd64.tar.gz"
      sha256 "63a24cea138b4ef9c7180dc57ee763cd4bad48658ed3b7dfc2979cc29466c627"
      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/cron-doctor/releases/download/v0.0.2/cron-doctor_linux_arm64.tar.gz"
      sha256 "747381fb82ea7e838dc3e67577a8e6481b88afaf1810e332edf713609b3610be"
      define_method(:install) do
        bin.install "cron-doctor"
      end
    end
  end

  test do
    system "#{bin}/cron-doctor", "--version"
  end
end
