# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlcGitignore < Formula
  desc "Opinionated .gitignore and .gitattributes for PLC projects"
  homepage "https://github.com/HeytalePazguato/plc-gitignore"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HeytalePazguato/plc-gitignore/releases/download/v0.1.0/plc-gitignore_0.1.0_darwin_amd64.tar.gz"
      sha256 "76d31a1f1b869ac028860b0a0a5852d0ab81a8cf1fbcd457ec714dd3107e3820"

      define_method(:install) do
        bin.install "plc-gitignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HeytalePazguato/plc-gitignore/releases/download/v0.1.0/plc-gitignore_0.1.0_darwin_arm64.tar.gz"
      sha256 "92c46ef09731a3de34d1ac1ce3b2c71258a4a5f2726f4ebbd16a7bb49ee29b03"

      define_method(:install) do
        bin.install "plc-gitignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/plc-gitignore/releases/download/v0.1.0/plc-gitignore_0.1.0_linux_amd64.tar.gz"
      sha256 "cbd16984a4dcc9fe13cc17a1d97dfa85321f30c892dc8d661a21473906dddab6"
      define_method(:install) do
        bin.install "plc-gitignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/plc-gitignore/releases/download/v0.1.0/plc-gitignore_0.1.0_linux_arm64.tar.gz"
      sha256 "103671a711dcb8c9e2c78b4f8d31de0a458b53d703c617e8414c93a61b76dd70"
      define_method(:install) do
        bin.install "plc-gitignore"
      end
    end
  end

  test do
    system "#{bin}/plc-gitignore", "version"
  end
end
