# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimerDoctor < Formula
  desc "Audit your systemd timers"
  homepage "https://github.com/HeytalePazguato/timer-doctor"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HeytalePazguato/timer-doctor/releases/download/v0.0.1/timer-doctor_darwin_amd64.tar.gz"
      sha256 "67f5b050ff3569746a67a21bd27fe234c36bffb46f4d2682cc1db4b836568c78"

      define_method(:install) do
        bin.install "timer-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HeytalePazguato/timer-doctor/releases/download/v0.0.1/timer-doctor_darwin_arm64.tar.gz"
      sha256 "09c2e6bfd1e5600a7ab6502b7c1798daa4406719b93dfae6afc46a564e09febf"

      define_method(:install) do
        bin.install "timer-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/timer-doctor/releases/download/v0.0.1/timer-doctor_linux_amd64.tar.gz"
      sha256 "954f094071a04522f78e3b6264f4cdf0334835238e3a7dc006b49cbb575fcead"
      define_method(:install) do
        bin.install "timer-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HeytalePazguato/timer-doctor/releases/download/v0.0.1/timer-doctor_linux_arm64.tar.gz"
      sha256 "90331f24475d29b18f26ad2bdf83a286dc87c9af6dcf1c952344b6816f5aa588"
      define_method(:install) do
        bin.install "timer-doctor"
      end
    end
  end

  test do
    system "#{bin}/timer-doctor", "--version"
  end
end
